//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fikalistaEntities : DbContext
    {
        public fikalistaEntities()
            : base("name=fikalistaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmailChanges> tblEmailChanges { get; set; }
        public virtual DbSet<tblFikaChanges> tblFikaChanges { get; set; }
        public virtual DbSet<tblFikaMembers> tblFikaMembers { get; set; }
    }
}
