//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailChanges
    {
        public int emailChangeId { get; set; }
        public int FikaMemberId { get; set; }
        public System.Guid ChangeToken { get; set; }
        public System.DateTime ChangeDoneDate { get; set; }
    }
}
