//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFikaChanges
    {
        public int changeId { get; set; }
        public int ChangeFromMemberId { get; set; }
        public Nullable<int> ChangeToMemberId { get; set; }
        public bool ChangeDone { get; set; }
        public System.Guid changeToken { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
    
        public virtual tblFikaChanges tblFikaChanges1 { get; set; }
        public virtual tblFikaChanges tblFikaChanges2 { get; set; }
    }
}
